- key: schedule
  url: /schedule/
- key: people
  url: /people/
- key: venue
  url: /venue/
  feature: venue
- key: sponsors
  url: /sponsors/
  feature: sponsors
- key: flyers
  url: /spread-the-word/
  feature: flyer
